import { User } from "../models/user.model";

let users: User[] = [
  {
    id: 1,
    user: "fulanosilva",
    email: "fulano@example.com",
    password: "senha123",
    name: "Fulano",
    lastName: "Silva",
    pronouns: "ele/dele",
    bio: "Olá! Sou Fulano Silva e sou apaixonado por games como Batman",
    followers: [26, 25, 24, 23, 22, 15, 14, 13, 11, 9, 2, 3],
    following: [5, 7, 8, 11, 12, 17, 21, 24, 27],
    blocked: []
  },
  {
    id: 2,
    user: "belagamer",
    email: "bela@example.com",
    password: "gamer123",
    name: "Bela",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Viciada em jogos desde a infância! Let's play!",
    followers: [3, 27, 24, 21, 20, 18, 16, 10, 9, 8, 7, 5],
    following: [1, 4, 6, 7, 12, 15, 19, 21, 22, 27],
    blocked: []
  },
  {
    id: 3,
    user: "joaogamer",
    email: "joao@example.com",
    password: "joaogamer456",
    name: "João",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Streamer e entusiasta de eSports. Jogos são minha vida!",
    followers: [27, 24, 23, 18, 17, 16, 12, 7, 5],
    following: [1, 2, 8, 11, 14, 15, 18, 21, 24, 26],
    blocked: []
  },
  {
    id: 4,
    user: "mariajogadora",
    email: "maria@example.com",
    password: "maria987",
    name: "Maria",
    lastName: "Jogadora",
    pronouns: "ela/dela",
    bio: "Gamer casual e amante de RPGs. Em busca de novos amigos!",
    followers: [27, 24, 19, 18, 13, 11, 9, 6, 2],
    following: [6, 8, 10, 15, 17, 23, 25, 27],
    blocked: []
  },
  {
    id: 5,
    user: "pedrogamer",
    email: "pedro@example.com",
    password: "pedro456",
    name: "Pedro",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Competitivo e sempre em busca do topo dos rankings.",
    followers: [26, 24, 23, 14, 13, 10, 9, 6, 1],
    following: [2, 3, 6, 7, 14, 20, 25, 26, 27],
    blocked: [2]
  },
  {
    id: 6,
    user: "anagame",
    email: "ana@example.com",
    password: "anagame789",
    name: "Ana",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Fã de jogos indie e narrativas envolventes.",
    followers: [27, 22, 18, 13, 8, 7, 5, 4, 2],
    following: [4, 5, 7, 9, 10, 11, 12, 18, 21, 22, 24, 26, 27],
    blocked: []
  },
  {
    id: 7,
    user: "lucasgamer",
    email: "lucas@example.com",
    password: "lucas789",
    name: "Lucas",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Sempre em busca de novos desafios nos jogos!",
    followers: [27, 25, 16, 10, 8, 6, 5, 2, 1],
    following: [2, 3, 6, 8, 12, 16, 19, 24, 26, 27],
    blocked: []
  },
  {
    id: 8,
    user: "andreagame",
    email: "andre@example.com",
    password: "andre123",
    name: "André",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Amante de jogos clássicos e retro-gaming.",
    followers: [26, 25, 13, 11, 10, 7, 4, 3, 1],
    following: [2, 6, 7, 11, 12, 15, 18, 20, 21, 22, 23, 24, 26, 27],
    blocked: []
  },
  {
    id: 9,
    user: "carlagamer",
    email: "carla@example.com",
    password: "carla456",
    name: "Carla",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Gamer hardcore e fã de jogos de estratégia.",
    followers: [26, 22, 21, 20, 19, 17, 15, 14, 11, 6],
    following: [1, 2, 4, 5, 11, 12, 14, 15, 20, 22, 23],
    blocked: []
  },
  {
    id: 10,
    user: "leonardogamer",
    email: "leonardo@example.com",
    password: "leonardo123",
    name: "Leonardo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Aventuras em mundos virtuais são minha paixão!",
    followers: [27, 25, 24, 17, 15, 14, 12, 11, 6, 4],
    following: [2, 5, 7, 8, 11, 12, 13, 16, 18, 23, 24],
    blocked: []
  },
  {
    id: 11,
    user: "claragame",
    email: "clara@example.com",
    password: "clara789",
    name: "Clara",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Jogadora desde criança, sempre pronta para uma nova jornada.",
    followers: [25, 24, 20, 17, 16, 14, 13, 10, 9, 8, 6, 3, 1],
    following: [1, 4, 8, 9, 10, 15, 18, 23, 24],
    blocked: []
  },
  {
    id: 12,
    user: "diegogamer",
    email: "diego@example.com",
    password: "diego456",
    name: "Diego",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Estratégia e táticas são a chave para a vitória!",
    followers: [24, 22, 18, 13, 10, 9, 8, 7, 6, 2, 1],
    following: [3, 10, 14, 15, 17, 27],
    blocked: []
  },
  {
    id: 13,
    user: "raquelgamer",
    email: "raquel@example.com",
    password: "raquel123",
    name: "Raquel",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Gamer casual e amante de jogos de quebra-cabeça.",
    followers: [23, 20, 17, 16, 10],
    following: [1, 4, 5, 6, 8, 11, 12, 15, 17, 19, 20, 25, 26],
    blocked: []
  },
  {
    id: 60,
    user: "Mathbonc",
    email: "Bonc@gmail.com",
    password: "40028922b",
    name: "Matheus",
    lastName: "Boncsidai",
    pronouns: "he/him",
    bio: "Hello There!",
    followers: [],
    following: [],
    blocked: []
  },
  {
    id: 14,
    user: "ricardogamer",
    email: "ricardo@example.com",
    password: "ricardo456",
    name: "Ricardo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Aventuras épicas e RPGs são minha paixão!",
    followers: [27, 25, 19, 18, 17, 12, 9, 5, 3],
    following: [1, 5, 9, 10, 11, 16, 17, 21, 23, 24, 27],
    blocked: []
  },
  {
    id: 15,
    user: "patriciagame",
    email: "patricia@example.com",
    password: "patricia123",
    name: "Patrícia",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Exploradora de mundos virtuais e quebra-cabeças desafiadores.",
    followers: [26, 22, 21, 17, 16, 13, 12, 11, 9, 8, 4, 3, 2],
    following: [1, 9, 10, 16, 18, 19, 20, 21, 22, 26, 27],
    blocked: []
  },
  {
    id: 16,
    user: "vitorjogador",
    email: "vitor@example.com",
    password: "vitor789",
    name: "Vitor",
    lastName: "Jogador",
    pronouns: "ele/dele",
    bio: "Gamer de estratégia e táticas militares. Sempre em busca de vitória!",
    followers: [20, 19, 18, 15, 14, 10, 7],
    following: [2, 3, 7, 11, 13, 15, 17, 21],
    blocked: []
  },
  {
    id: 17,
    user: "camilagamer",
    email: "camila@example.com",
    password: "camila456",
    name: "Camila",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Amante de jogos de simulação e construção de cidades.",
    followers: [21, 20, 16, 14, 13, 12, 4, 1],
    following: [3, 9, 10, 11, 13, 14, 15, 20, 23],
    blocked: []
  },
  {
    id: 18,
    user: "fernandogame",
    email: "fernando@example.com",
    password: "fernando123",
    name: "Fernando",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Conquistador de mundos virtuais e estratégia em tempo real.",
    followers: [24, 23, 21, 15, 11, 10, 8, 6, 3],
    following: [2, 3, 4, 6, 12, 14, 16, 20, 21, 25, 26],
    blocked: []
  },
  {
    id: 19,
    user: "lucianogamer",
    email: "luciano@example.com",
    password: "luciano789",
    name: "Luciano",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Gamer competitivo e fã de jogos de tiro em primeira pessoa.",
    followers: [26, 25, 23, 21, 20, 15, 13, 7, 2],
    following: [4, 9, 14, 16, 20, 24, 27],
    blocked: []
  },
  {
    id: 20,
    user: "isabelgame",
    email: "isabel@example.com",
    password: "isabel456",
    name: "Isabel",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Aventureira em mundos mágicos e RPGs de fantasia.",
    followers: [27, 21, 19, 18, 17, 15, 13, 9, 8, 5],
    following: [2, 9, 11, 13, 16, 17, 19, 25, 27],
    blocked: []
  },
  {
    id: 21,
    user: "henriquegamer",
    email: "henrique@example.com",
    password: "henrique123",
    name: "Henrique",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Estrategista em jogos de guerra e comandante de exércitos virtuais.",
    followers: [26, 24, 23, 22, 18, 16, 15, 14, 8, 6, 3, 2, 1],
    following: [2, 9, 15, 17, 18, 19, 20, 27],
    blocked: []
  },
  {
    id: 22,
    user: "larissagame",
    email: "larissa@example.com",
    password: "larissa789",
    name: "Larissa",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Gamer de aventuras e caçadora de tesouros virtuais.",
    followers: [15, 9, 8, 6, 2],
    following: [1, 6, 9, 12, 15, 21, 24, 25, 26],
    blocked: []
  },
  {
    id: 23,
    user: "marcelogamer",
    email: "marcelo@example.com",
    password: "marcelo456",
    name: "Marcelo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Fã de jogos de estratégia e construção de impérios virtuais.",
    followers: [25, 17, 14, 11, 10, 9, 8, 4],
    following: [1, 3, 5, 13, 18, 19, 21],
    blocked: []
  },
  {
    id: 24,
    user: "patygamer",
    email: "paty@example.com",
    password: "paty123",
    name: "Paty",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Exploradora de mundos virtuais e amante de jogos de simulação.",
    followers: [25, 22, 19, 14, 11, 10, 8, 7, 6, 3, 1],
    following: [1, 2, 3, 4, 5, 10, 11, 12, 18, 21],
    blocked: []
  },
  {
    id: 25,
    user: "marcosgame",
    email: "marcos@example.com",
    password: "marcos456",
    name: "Marcos",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Gamer de estratégia e conquista virtual.",
    followers: [22, 20, 18, 13, 5, 4],
    following: [1, 7, 8, 10, 11, 14, 19, 23, 24, 27],
    blocked: []
  },
  {
    id: 26,
    user: "anaclaragamer",
    email: "anaclara@example.com",
    password: "anaclara123",
    name: "Ana Clara",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Aventureira virtual e fã de jogos de sobrevivência.",
    followers: [22, 18, 15, 13, 8, 7, 6, 5, 3],
    following: [1, 5, 8, 9, 15, 19, 21],
    blocked: []
  },
  {
    id: 27,
    user: "carlosgamer",
    email: "carlos@example.com",
    password: "carlos789",
    name: "Carlos",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Gamer casual e fã de jogos de plataforma.",
    followers: [25, 21, 20, 19, 15, 14, 12, 8, 7, 6, 5, 4, 2, 1],
    following: [2, 3, 4, 6, 7, 10, 14, 20],
    blocked: []
  }
]

export default users;