import { User } from "../models/user.model";

let users: User[] = [
  {
    id: 1,
    user: "fulanosilva",
    email: "fulano@example.com",
    password: "senha123",
    name: "Fulano",
    lastName: "Silva",
    pronouns: "ele/dele",
    bio: "Olá! Sou Fulano Silva e sou apaixonado por games como Batman",
    followers: [2, 3, 8, 9, 10, 11, 12, 13, 14, 15, 16],
    following: [6, 7, 8, 9, 10, 11, 12],
    blocked: []
  },
  {
    id: 2,
    user: "belagamer",
    email: "bela@example.com",
    password: "gamer123",
    name: "Bela",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Viciada em jogos desde a infância! Let's play!",
    followers: [3],
    following: [1],
    blocked: []
  },
  {
    id: 3,
    user: "joaogamer",
    email: "joao@example.com",
    password: "joaogamer456",
    name: "João",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Streamer e entusiasta de eSports. Jogos são minha vida!",
    followers: [3],
    following: [2, 1],
    blocked: []
  },
  {
    id: 4,
    user: "mariajogadora",
    email: "maria@example.com",
    password: "maria987",
    name: "Maria",
    lastName: "Jogadora",
    pronouns: "ela/dela",
    bio: "Gamer casual e amante de RPGs. Em busca de novos amigos!",
    followers: [],
    following: [],
    blocked: []
  },
  {
    id: 5,
    user: "pedrogamer",
    email: "pedro@example.com",
    password: "pedro456",
    name: "Pedro",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Competitivo e sempre em busca do topo dos rankings.",
    followers: [],
    following: [],
    blocked: [2]
  },
  {
    id: 6,
    user: "anagame",
    email: "ana@example.com",
    password: "anagame789",
    name: "Ana",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Fã de jogos indie e narrativas envolventes.",
    followers: [1, 2, 4, 5],
    following: [],
    blocked: []
  },
  {
    id: 7,
    user: "lucasgamer",
    email: "lucas@example.com",
    password: "lucas789",
    name: "Lucas",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Sempre em busca de novos desafios nos jogos!",
    followers: [2, 8],
    following: [2, 8],
    blocked: []
  },
  {
    id: 8,
    user: "andreagame",
    email: "andre@example.com",
    password: "andre123",
    name: "André",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Amante de jogos clássicos e retro-gaming.",
    followers: [2, 7],
    following: [2, 7],
    blocked: []
  },
  {
    id: 9,
    user: "carlagamer",
    email: "carla@example.com",
    password: "carla456",
    name: "Carla",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Gamer hardcore e fã de jogos de estratégia.",
    followers: [10, 11],
    following: [10, 11, 12],
    blocked: []
  },
  {
    id: 10,
    user: "leonardogamer",
    email: "leonardo@example.com",
    password: "leonardo123",
    name: "Leonardo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Aventuras em mundos virtuais são minha paixão!",
    followers: [9, 11],
    following: [9, 11],
    blocked: []
  },
  {
    id: 11,
    user: "claragame",
    email: "clara@example.com",
    password: "clara789",
    name: "Clara",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Jogadora desde criança, sempre pronta para uma nova jornada.",
    followers: [9, 10],
    following: [9, 10],
    blocked: []
  },
  {
    id: 12,
    user: "diegogamer",
    email: "diego@example.com",
    password: "diego456",
    name: "Diego",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Estratégia e táticas são a chave para a vitória!",
    followers: [9, 1, 2, 3, 4, 5, 6, 7],
    following: [9, 2, 3, 4],
    blocked: []
  },
  {
    id: 13,
    user: "raquelgamer",
    email: "raquel@example.com",
    password: "raquel123",
    name: "Raquel",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Gamer casual e amante de jogos de quebra-cabeça.",
    followers: [],
    following: [9, 10, 11],
    blocked: []
  },
  {
    id: 60,
    user: "Mathbonc",
    email: "Bonc@gmail.com",
    password: "40028922b",
    name: "Matheus",
    lastName: "Boncsidai",
    pronouns: "he/him",
    bio: "Hello There!",
    followers: [],
    following: [],
    blocked: []
  },
  {
    id: 14,
    user: "ricardogamer",
    email: "ricardo@example.com",
    password: "ricardo456",
    name: "Ricardo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Aventuras épicas e RPGs são minha paixão!",
    followers: [15, 16],
    following: [15],
    blocked: []
  },
  {
    id: 15,
    user: "patriciagame",
    email: "patricia@example.com",
    password: "patricia123",
    name: "Patrícia",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Exploradora de mundos virtuais e quebra-cabeças desafiadores.",
    followers: [14],
    following: [14],
    blocked: []
  },
  {
    id: 16,
    user: "vitorjogador",
    email: "vitor@example.com",
    password: "vitor789",
    name: "Vitor",
    lastName: "Jogador",
    pronouns: "ele/dele",
    bio: "Gamer de estratégia e táticas militares. Sempre em busca de vitória!",
    followers: [14],
    following: [],
    blocked: []
  },
  {
    id: 17,
    user: "camilagamer",
    email: "camila@example.com",
    password: "camila456",
    name: "Camila",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Amante de jogos de simulação e construção de cidades.",
    followers: [18, 19],
    following: [18],
    blocked: []
  },
  {
    id: 18,
    user: "fernandogame",
    email: "fernando@example.com",
    password: "fernando123",
    name: "Fernando",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Conquistador de mundos virtuais e estratégia em tempo real.",
    followers: [17],
    following: [17],
    blocked: []
  },
  {
    id: 19,
    user: "lucianogamer",
    email: "luciano@example.com",
    password: "luciano789",
    name: "Luciano",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Gamer competitivo e fã de jogos de tiro em primeira pessoa.",
    followers: [17],
    following: [],
    blocked: []
  },
  {
    id: 20,
    user: "isabelgame",
    email: "isabel@example.com",
    password: "isabel456",
    name: "Isabel",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Aventureira em mundos mágicos e RPGs de fantasia.",
    followers: [],
    following: [17, 18],
    blocked: []
  },
  {
    id: 21,
    user: "henriquegamer",
    email: "henrique@example.com",
    password: "henrique123",
    name: "Henrique",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Estrategista em jogos de guerra e comandante de exércitos virtuais.",
    followers: [17, 18],
    following: [17, 18],
    blocked: []
  },
  {
    id: 22,
    user: "larissagame",
    email: "larissa@example.com",
    password: "larissa789",
    name: "Larissa",
    lastName: "Game",
    pronouns: "ela/dela",
    bio: "Gamer de aventuras e caçadora de tesouros virtuais.",
    followers: [],
    following: [17],
    blocked: []
  },
  {
    id: 23,
    user: "marcelogamer",
    email: "marcelo@example.com",
    password: "marcelo456",
    name: "Marcelo",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Fã de jogos de estratégia e construção de impérios virtuais.",
    followers: [24],
    following: [24],
    blocked: []
  },
  {
    id: 24,
    user: "patygamer",
    email: "paty@example.com",
    password: "paty123",
    name: "Paty",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Exploradora de mundos virtuais e amante de jogos de simulação.",
    followers: [23],
    following: [23],
    blocked: []
  },
  {
    id: 25,
    user: "marcosgame",
    email: "marcos@example.com",
    password: "marcos456",
    name: "Marcos",
    lastName: "Game",
    pronouns: "ele/dele",
    bio: "Gamer de estratégia e conquista virtual.",
    followers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 26],
    following: [26],
    blocked: []
  },
  {
    id: 26,
    user: "anaclaragamer",
    email: "anaclara@example.com",
    password: "anaclara123",
    name: "Ana Clara",
    lastName: "Gamer",
    pronouns: "ela/dela",
    bio: "Aventureira virtual e fã de jogos de sobrevivência.",
    followers: [25],
    following: [25],
    blocked: []
  },
  {
    id: 27,
    user: "carlosgamer",
    email: "carlos@example.com",
    password: "carlos789",
    name: "Carlos",
    lastName: "Gamer",
    pronouns: "ele/dele",
    bio: "Gamer casual e fã de jogos de plataforma.",
    followers: [28],
    following: [28],
    blocked: []
  }
]

export default users;